import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, CalendarCheck, CheckCircle2, Clapperboard, Film, MessageCircle, PackageCheck, Upload, Wand2 } from 'lucide-react'
import { Card, Reveal, SectionHeader } from '../components/ui'
import { services, testimonials } from '../data/mockData'
import { brand } from '../data/brandData'
import { featuredPortfolioItems } from '../data/portfolioData'
const steps=[['Pilih paket',PackageCheck],['Booking',CalendarCheck],['Upload pembayaran',Upload],['Produksi',Clapperboard],['Editing progress',Wand2],['Selesai',CheckCircle2]]
export function Hero(){const hero=featuredPortfolioItems.slice(0,3);return <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32"><div className="container-premium grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><Reveal><div className="mb-5 inline-flex items-center gap-3 rounded-full border border-gold/25 bg-gold/10 px-4 py-2"><img src={brand.logo} alt="Mellogang logo" className="h-7 w-7 rounded-full object-cover"/><span className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">{brand.handle} · {brand.location}</span></div><p className="eyebrow">Premium Creative Studio</p><h1 className="headline mt-5">{brand.tagline}</h1><p className="subtle mt-6 max-w-2xl text-lg">{brand.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary" to="/katalog">Lihat Paket <ArrowRight size={17}/></Link><Link className="btn-secondary" to="/portofolio">Lihat Portfolio</Link></div><div className="mt-9 grid grid-cols-3 gap-3 max-w-lg">{[['Wedding','Story'],['Ceremony','Moment'],['Bali','Production']].map(x=><Card key={x[0]} className="rounded-3xl p-4"><b className="text-xl text-cream">{x[0]}</b><p className="text-xs text-cream/45">{x[1]}</p></Card>)}</div></Reveal><div className="relative min-h-[520px]">{hero.map((item,i)=><motion.div key={item.id} className={`absolute overflow-hidden rounded-[2rem] border border-white/15 shadow-glow ${['left-8 top-6 h-72 w-56','right-0 top-28 h-80 w-64','bottom-4 left-20 h-64 w-80'][i]}`} animate={{y:[0,i%2?14:-12,0]}} transition={{duration:7+i,repeat:Infinity}}><img className="h-full w-full object-cover" src={item.thumbnail}/><div className="absolute inset-0 bg-gradient-to-t from-black/45 to-transparent"/></motion.div>)}<div className="absolute inset-10 -z-10 rounded-full bg-gold/20 blur-3xl"/></div></div></section>}
export function Services(){return <section className="section-pad"><div className="container-premium"><SectionHeader eyebrow="Services" title="Visual production untuk semua momen penting">Wedding, ceremony, graduation, event, and creative visual production — disusun dengan direction, schedule, payment flow, dan tracking progress yang jelas.</SectionHeader><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=><Reveal delay={i*.04} key={s}><Card className="group min-h-44"><Film className="text-gold"/><h3 className="mt-8 text-2xl font-semibold">{s}</h3><p className="subtle mt-3">Konsep visual premium, clean editing, dan deliverable siap publikasi.</p></Card></Reveal>)}</div></div></section>}
export function PortfolioPreview(){return <section className="section-pad"><div className="container-premium"><SectionHeader eyebrow="Portfolio" title="Real Stories, Cinematic Frames">Wedding, ceremony, graduation, event, and creative visual production. Semua visual di sini memakai aset real Mellogang dari Instagram/YouTube.</SectionHeader><div className="grid gap-4 md:grid-cols-3">{featuredPortfolioItems.slice(0,6).map((p,i)=><Reveal delay={i*.04} key={p.id}><Link to="/portofolio" className={`group block overflow-hidden rounded-[2rem] border border-white/10 bg-white/5 ${i===0?'md:col-span-2':''}`}><img className="h-80 w-full object-cover transition duration-700 group-hover:scale-105" src={p.thumbnail}/><div className="p-5"><p className="badge">{p.source} · {p.category}</p><h3 className="mt-3 text-xl font-semibold">{p.title}</h3><p className="subtle mt-2 line-clamp-2">{p.description}</p></div></Link></Reveal>)}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary" to="/portofolio">Lihat Portfolio <ArrowRight size={17}/></Link><a className="btn-secondary" href={brand.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={17}/>Booking via WhatsApp</a></div></div></section>}
export function HowItWorks(){return <section className="section-pad"><div className="container-premium"><SectionHeader center eyebrow="Workflow" title="Tracking production dari booking sampai selesai"/><div className="grid gap-4 md:grid-cols-3 lg:grid-cols-6">{steps.map(([label,Icon],i)=><Reveal delay={i*.04} key={label}><Card className="h-full rounded-3xl text-center"><Icon className="mx-auto text-gold"/><p className="mt-4 text-sm font-semibold">{label}</p></Card></Reveal>)}</div></div></section>}
export function Testimonials(){return <section className="section-pad"><div className="container-premium"><SectionHeader eyebrow="Trust" title="Dipercaya untuk momen yang gak bisa diulang"/><div className="grid gap-4 md:grid-cols-3">{testimonials.map(t=><Card key={t.name}><p className="text-lg leading-8 text-cream/82">“{t.text}”</p><p className="mt-6 font-semibold text-gold">{t.name}</p></Card>)}</div></div></section>}
export function ContactCTA(){return <section className="pb-20"><div className="container-premium"><Card className="overflow-hidden rounded-[2.5rem] p-8 md:p-12"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow">Ready when you are</p><h2 className="mt-4 text-3xl font-semibold sm:text-5xl">Bikin visual lo kerasa cinematic dari first impression.</h2></div><a className="btn-primary" href={brand.whatsapp} target="_blank" rel="noreferrer">Konsultasi Sekarang <ArrowRight size={17}/></a></div></Card></div></section>}
