import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, CalendarCheck, CheckCircle2, Clapperboard, CreditCard, Film, Images, PackageCheck, Upload, Wand2 } from 'lucide-react'
import { Card, Reveal, SectionHeader } from '../components/ui'
import { portfolio, services, testimonials } from '../data/mockData'
import { brand } from '../data/brandData'
const steps=[['Pilih paket',PackageCheck],['Booking',CalendarCheck],['Upload pembayaran',Upload],['Produksi',Clapperboard],['Editing progress',Wand2],['Selesai',CheckCircle2]]
export function Hero(){return <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32"><div className="container-premium grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><Reveal><div className="mb-5 inline-flex items-center gap-3 rounded-full border border-gold/25 bg-gold/10 px-4 py-2"><img src={brand.logo} alt="Mellogang logo" className="h-7 w-7 rounded-full object-cover"/><span className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">{brand.handle} · {brand.tagline.replace('Mellogang Visuals | ', '')}</span></div><p className="eyebrow">Premium Creative Studio</p><h1 className="headline mt-5">Capture Your Moment, Tell Your Story.</h1><p className="subtle mt-6 max-w-2xl text-lg">{brand.name} mengubah momen wedding, event, brand, dan karya kreatif jadi visual cinematic yang terasa mahal, rapi, dan emotional — dengan identitas visual dark-air black dan aksen turquoise dari brand asli.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary" to="/katalog">Lihat Paket <ArrowRight size={17}/></Link><Link className="btn-secondary" to="/status-pesanan">Cek Status Pesanan</Link></div><div className="mt-9 grid grid-cols-3 gap-3 max-w-lg">{[['128+','Projects'],['4.9/5','Client Rating'],['24h','Fast Response']].map(x=><Card key={x[1]} className="rounded-3xl p-4"><b className="text-2xl text-cream">{x[0]}</b><p className="text-xs text-cream/45">{x[1]}</p></Card>)}</div></Reveal><div className="relative min-h-[520px]"><motion.div className="absolute left-10 top-6 h-72 w-56 overflow-hidden rounded-[2rem] border border-white/15 shadow-glow" animate={{y:[0,-12,0]}} transition={{duration:7,repeat:Infinity}}><img className="h-full w-full object-cover" src={portfolio[0].thumb}/></motion.div><motion.div className="absolute right-0 top-28 h-80 w-64 overflow-hidden rounded-[2.5rem] border border-white/15 shadow-soft" animate={{y:[0,14,0]}} transition={{duration:8,repeat:Infinity}}><img className="h-full w-full object-cover" src={portfolio[2].thumb}/></motion.div><motion.div className="absolute bottom-4 left-20 h-64 w-80 overflow-hidden rounded-[2.5rem] border border-gold/30 shadow-glow" animate={{y:[0,-10,0]}} transition={{duration:9,repeat:Infinity}}><img className="h-full w-full object-cover" src={portfolio[3].thumb}/></motion.div><div className="absolute inset-10 -z-10 rounded-full bg-gold/20 blur-3xl"/></div></div></section>}
export function Services(){return <section className="section-pad"><div className="container-premium"><SectionHeader eyebrow="Services" title="Visual production untuk semua momen penting">Dari wedding sampai brand campaign, semua disusun dengan direction, schedule, payment flow, dan tracking progress yang jelas.</SectionHeader><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=><Reveal delay={i*.04} key={s}><Card className="group min-h-44"><Film className="text-gold"/><h3 className="mt-8 text-2xl font-semibold">{s}</h3><p className="subtle mt-3">Konsep visual premium, clean editing, dan deliverable siap publikasi.</p></Card></Reveal>)}</div></div></section>}
export function PortfolioPreview(){return <section className="section-pad"><div className="container-premium"><SectionHeader eyebrow="Portfolio" title="Featured frames with cinematic mood"/><div className="grid gap-4 md:grid-cols-3">{portfolio.slice(0,3).map((p,i)=><Reveal delay={i*.06} key={p.id_portfolio}><Link to="/portofolio" className="group block overflow-hidden rounded-[2rem] border border-white/10 bg-white/5"><img className="h-80 w-full object-cover transition duration-700 group-hover:scale-105" src={p.thumb}/><div className="p-5"><p className="badge">{p.kategori}</p><h3 className="mt-3 text-xl font-semibold">{p.judul}</h3></div></Link></Reveal>)}</div></div></section>}
export function HowItWorks(){return <section className="section-pad"><div className="container-premium"><SectionHeader center eyebrow="Workflow" title="Tracking production dari booking sampai selesai"/><div className="grid gap-4 md:grid-cols-3 lg:grid-cols-6">{steps.map(([label,Icon],i)=><Reveal delay={i*.04} key={label}><Card className="h-full rounded-3xl text-center"><Icon className="mx-auto text-gold"/><p className="mt-4 text-sm font-semibold">{label}</p></Card></Reveal>)}</div></div></section>}
export function Testimonials(){return <section className="section-pad"><div className="container-premium"><SectionHeader eyebrow="Trust" title="Dipercaya client untuk momen yang gak bisa diulang"/><div className="grid gap-4 md:grid-cols-3">{testimonials.map(t=><Card key={t.name}><p className="text-lg leading-8 text-cream/82">“{t.text}”</p><p className="mt-6 font-semibold text-gold">{t.name}</p></Card>)}</div></div></section>}
export function ContactCTA(){return <section className="pb-20"><div className="container-premium"><Card className="overflow-hidden rounded-[2.5rem] p-8 md:p-12"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow">Ready when you are</p><h2 className="mt-4 text-3xl font-semibold sm:text-5xl">Bikin visual lo kerasa cinematic dari first impression.</h2></div><Link className="btn-primary" to="/kontak">Konsultasi Sekarang <ArrowRight size={17}/></Link></div></Card></div></section>}
