import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Search, Upload } from 'lucide-react'
import { api, backendUrl } from '../lib/api'
import { brand } from '../data/brandData'
import { getDemoSession } from '../data/demoUserData'
import { mockOrders } from '../data/mockOrders'
import { rupiah } from '../lib/utils'
import { Card, EmptyState, SectionHeader, StatusBadge } from '../components/ui'

function OrderCard({ order }){const navigate=useNavigate();return <Card className="mt-6"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="eyebrow">{order.kode || order.kode_pemesanan}</p><h3 className="mt-3 text-3xl font-semibold">{order.packageName || order.nama_paket}</h3><p className="subtle mt-2">{order.eventType || 'Visual Production'} · {order.eventDate || order.tanggal_acara || '-'}</p><p className="subtle">{order.eventLocation || '-'}</p></div><div className="flex flex-wrap gap-2"><StatusBadge status={order.paymentStatus || order.status_pemesanan}/><StatusBadge status={order.productionStatus || order.status_produksi}/></div></div><div className="mt-8 grid gap-4 md:grid-cols-4"><div><p className="text-cream/45">Total</p><b>{rupiah(order.total_biaya || 0)}</b></div><div><p className="text-cream/45">Progress editing</p><b>{order.editingProgress || order.progress || 0}%</b></div><div><p className="text-cream/45">Editor</p><b>{order.editorName || '-'}</b></div><div><p className="text-cream/45">Invoice</p>{order.invoiceCode ? <button className="text-gold underline" onClick={()=>navigate(`/invoice?kode=${order.invoiceCode || order.kode}`)}>Lihat Invoice</button> : <p className="text-sm text-cream/45">Invoice final akan tersedia setelah pembayaran diverifikasi.</p>}</div></div><div className="mt-8 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gold" style={{width:`${order.editingProgress || order.progress || 0}%`}}/></div><div className="mt-8 grid gap-3 md:grid-cols-3">{(order.timeline || []).map(step=><div key={step.label} className={`rounded-2xl border p-4 ${step.status==='done'?'border-gold/30 bg-gold/10':step.status==='active'?'border-white/20 bg-white/10':'border-white/10 bg-white/5'}`}><p className="text-sm font-semibold">{step.label}</p><p className="mt-1 text-xs text-cream/45">{step.date}</p></div>)}</div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><a className="btn-secondary" href={backendUrl('/pelanggan/pembayaran')}><Upload size={16}/>Upload Bukti Pembayaran</a><a className="btn-secondary" href={brand.whatsapp} target="_blank" rel="noreferrer"><img src={brand.socialIcons.whatsapp} className="h-5 w-5" alt="WhatsApp"/>Tanya via WhatsApp</a></div>{order.notes&&<p className="subtle mt-5">{order.notes}</p>}</Card>}

export default function StatusPesanan(){const [kode,setKode]=useState(''),[order,setOrder]=useState(null),[searched,setSearched]=useState(false),[loading,setLoading]=useState(false),[session,setSession]=useState(null);useEffect(()=>setSession(getDemoSession()),[]);async function submit(e){e.preventDefault();setLoading(true);setSearched(true);const demo=mockOrders.find(o=>[o.kode,o.kode_pemesanan,o.invoiceCode].includes(kode.trim()));setOrder(demo || await api.orderStatus(kode));setLoading(false)} return <section className="section-pad"><div className="container-premium"><SectionHeader eyebrow="Order Tracking" title="Cek status pesanan dengan timeline yang jelas">Masukkan kode pemesanan atau login demo untuk melihat order, progress editing, dan invoice.</SectionHeader><Card><form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row"><input className="input-dark" value={kode} onChange={e=>setKode(e.target.value)} placeholder="Contoh: MLG-ORD-2026-001 atau INV-MLG-2026-001"/><button className="btn-primary" disabled={loading}><Search size={16}/>{loading?'Mencari...':'Cek Status'}</button></form></Card>{session&&<div className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-semibold text-cream">Pesanan {session.name}</h2><span className="badge">Demo customer session</span></div>{mockOrders.filter(o=>o.customerEmail===session.email).map(o=><OrderCard key={o.id} order={o}/>)}</div>}{searched&&!order&&!loading&&<div className="mt-6"><EmptyState title="Pesanan tidak ditemukan" text="Cek ulang kode pemesanan atau gunakan demo login dummy@dummy.com / dummy."/><a className="btn-secondary mt-4" href={backendUrl('/status-pesanan')}>Buka Status Backend</a></div>}{order&&<OrderCard order={order}/>} {!session&&<Card className="mt-8 text-center"><h3 className="text-2xl font-semibold">Login untuk melihat invoice dan order pelanggan.</h3><p className="subtle mt-2">Demo: dummy@dummy.com / dummy.</p><Link className="btn-primary mt-5" to="/auth?mode=signin">Login Demo</Link></Card>}</div></section>}
