import { useEffect } from 'react'
import { ArrowLeft, ArrowRight, ExternalLink, X } from 'lucide-react'
import { brand } from '../../data/brandData'
import SmartImage from '../SmartImage'
export default function PortfolioModal({ item, onClose, onNavigate }) {
  useEffect(() => { const onKey=e=>{ if(e.key==='Escape') onClose(); if(e.key==='ArrowRight') onNavigate(1); if(e.key==='ArrowLeft') onNavigate(-1) }; window.addEventListener('keydown', onKey); return ()=>window.removeEventListener('keydown', onKey) }, [onClose,onNavigate])
  if (!item) return null
  const isYoutube = item.type === 'youtube' && item.embedUrl
  return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/82 p-3 backdrop-blur-2xl" onClick={onClose}><div className="relative max-h-[94vh] w-full max-w-6xl overflow-hidden rounded-[2rem] border border-white/10 bg-[#090909] shadow-2xl" onClick={e=>e.stopPropagation()}><button className="absolute right-4 top-4 z-10 rounded-full bg-black/65 p-3 text-white backdrop-blur-xl" onClick={onClose}><X/></button><div className="grid lg:grid-cols-[1.25fr_.75fr]"><div className="min-h-[360px] bg-black">{isYoutube ? <iframe className="aspect-video h-full min-h-[360px] w-full" src={item.embedUrl} title={item.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/> : <div className="h-full max-h-[82vh]"><SmartImage src={item.thumbnail} alt={item.title} objectPosition={item.objectPosition}/></div>}</div><div className="p-6 sm:p-8"><p className="eyebrow">{item.source} · {item.category}</p><h3 className="mt-4 text-3xl font-semibold tracking-[-.04em] text-cream sm:text-5xl">{item.title}</h3><p className="mt-5 text-sm leading-7 text-cream/68">{item.description}</p><div className="mt-6 flex flex-wrap gap-2">{item.tags?.map(t=><span key={t} className="badge">{t}</span>)}</div><div className="mt-8 flex flex-col gap-3"><a className="btn-primary" href={item.url} target="_blank" rel="noreferrer"><img src={brand.socialIcons[item.source==='YouTube'?'youtube':'instagram']} alt={item.source} className="h-5 w-5"/>{item.source==='YouTube'?'Watch on YouTube':'View on Instagram'} <ExternalLink size={16}/></a><a className="btn-secondary" href={brand.whatsapp} target="_blank" rel="noreferrer"><img src={brand.socialIcons.whatsapp} alt="WhatsApp" className="h-5 w-5"/>Book Similar Concept</a></div><div className="mt-8 flex justify-between"><button className="btn-secondary" onClick={()=>onNavigate(-1)}><ArrowLeft size={16}/>Prev</button><button className="btn-secondary" onClick={()=>onNavigate(1)}>Next<ArrowRight size={16}/></button></div></div></div></div></div>
}
